name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
  
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4.0.0        

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Test
      run: go test -v ./...
